name: campus_map_app
description: "A new Flutter project."
publish_to: 'none' # (ì£¼ì˜) pub.devì— ì‹¤ìˆ˜ë¡œ ì˜¬ë¦¬ëŠ” ê±¸ ë§‰ì•„ì£¼ëŠ” ì˜µì…˜

version: 1.0.0+1 # ì•± ë²„ì „

environment:
  sdk: ^3.7.2 # Dart SDK ë²„ì „

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # iOS ìŠ¤íƒ€ì¼ ì•„ì´ì½˜ ì‚¬ìš©
  flutter_svg: ^2.0.7    # svg íŒ¨í‚¤ì§€
  google_fonts: ^6.1.0  # google_fontsë¥¼ dependencies ì•„ë˜ì— ì¶”ê°€
  intl: ^0.18.1         # ì‹œê°„ íŒ¨í‚¤ì§€

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # ì½”ë”© ìŠ¤íƒ€ì¼ ì²´í¬ ë„êµ¬ (ì¢‹ì€ ì½”ë“œ ì“°ê²Œ ë„ì™€ì¤Œ)

flutter:
  uses-material-design: true # ë¨¸í‹°ë¦¬ì–¼ ë””ìì¸ ì‚¬ìš© (ê¸°ë³¸ Flutter ì•„ì´ì½˜ ì‚¬ìš© ê°€ëŠ¥)

  assets: # ğŸ“· ì•±ì— ì´ë¯¸ì§€ ì¶”ê°€í•  ë•Œ
    - assets/images/logo.png
    - assets/images/campus_map.png
    - assets/images/it_building_1f_map.png # assets/images í´ë” ì•ˆì— ìˆëŠ” ëª¨ë“  ì´ë¯¸ì§€ ì‚¬ìš© ê°€ëŠ¥
    - assets/images/it_building_2f_map.png
    - assets/images/it_building_3f_map.png
    - assets/images/it_building_4f_map.png
    - assets/images/it_building_5f_map.png
    - assets/images/it_building_6f_map.png
    - assets/images/it_building_7f_map.png
    - assets/images/it_building_8f_map.png
    - assets/images/it_building_9f_map.png
    - assets/images/it_building_10f_map.png
    - assets/data/classroom_schedule_final.json # JSON íŒŒì¼ ì¶”ê°€ (ê°•ì˜ì‹¤ ì‹œê°„í‘œ ë°ì´í„°)
    - assets/icons/
